export enum MESSAGE_PATTERNS {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  KEEPALIVE = 'KEEPALIVE',
}

export enum DEVICE_MESSAGE_PATTERNS {
  DEVICE_REGISTER = 'DEVICE_REGISTER',
  DEVICE_GET = 'DEVICE_GET',
  DEVICE_REMOVE = 'DEVICE_REMOVE',
  DEVICE_GET_OBJECTID = 'DEVICE_GET_OBJECTID',
}
