export enum DEVICE_MESSAGE_PATTERNS {
  DEVICE_REGISTER = 'DEVICE_REGISTER',
  DEVICE_GET = 'DEVICE_GET',
  DEVICE_REMOVE = 'DEVICE_REMOVE',
  DEVICE_RENAME = 'DEVICE_RENAME',
}

export enum AUTHENTICATION_MESSAGE_PATTERNS {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
}

export enum USERS_MESSAGE_PATTERNS {
  GET_USER = 'GET_USER',
  CREATE_USER = 'CREATE_USER',
  REMOVE_USER = 'REMOVE_USER',
}
